/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx}', './components/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        navy: { DEFAULT: '#0B1F3A', mid: '#122448', light: '#1C3560' },
        green: { DEFAULT: '#00B67A', dark: '#009966', pale: '#E6F9F2' },
        amber: '#F59E0B',
        'off-white': '#F7F9FC',
        border: '#DDE4EE',
        gray: {
          50: '#F0F4F9',
          100: '#EEF1F6',
          300: '#C8D0DC',
          400: '#9BAAB8',
          500: '#7A8BA0',
          600: '#4E6074',
          700: '#3D4F63',
        },
      },
      fontFamily: {
        sans: ['var(--font-outfit)', 'Outfit', 'sans-serif'],
        serif: ['var(--font-fraunces)', 'Fraunces', 'serif'],
      },
      boxShadow: {
        sm: '0 2px 8px rgba(11,31,58,0.06)',
        md: '0 8px 28px rgba(11,31,58,0.10)',
        lg: '0 20px 60px rgba(11,31,58,0.14)',
        xl: '0 32px 80px rgba(11,31,58,0.18)',
        'green-glow': '0 8px 32px rgba(0,182,122,0.3)',
      },
      keyframes: {
        ping: { '75%,100%': { transform: 'scale(2)', opacity: '0' } },
        fadeUp: { from: { opacity: '0', transform: 'translateY(28px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.94)' }, to: { opacity: '1', transform: 'scale(1)' } },
        slideRight: { from: { opacity: '0', transform: 'translateX(-24px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        slideLeft: { from: { opacity: '0', transform: 'translateX(24px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        pulseDot: { '0%,100%': { opacity: '1', transform: 'scale(1)' }, '50%': { opacity: '0.4', transform: 'scale(0.6)' } },
        shimmer: { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        float: { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-8px)' } },
        heroRise: { from: { opacity: '0', transform: 'translateY(48px) scale(0.97)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        countUp: { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        marquee: { '0%': { transform: 'translateX(0%)' }, '100%': { transform: 'translateX(-50%)' } },
        wiggle: { '0%,100%': { transform: 'rotate(-6deg)' }, '50%': { transform: 'rotate(6deg)' } },
      },
      animation: {
        ping: 'ping 2s cubic-bezier(0,0,0.2,1) infinite',
        fadeUp: 'fadeUp 0.7s cubic-bezier(0.16,1,0.3,1) both',
        fadeIn: 'fadeIn 0.6s ease both',
        scaleIn: 'scaleIn 0.8s cubic-bezier(0.16,1,0.3,1) both',
        slideRight: 'slideRight 0.7s cubic-bezier(0.16,1,0.3,1) both',
        slideLeft: 'slideLeft 0.7s cubic-bezier(0.16,1,0.3,1) both',
        pulseDot: 'pulseDot 1.5s infinite',
        shimmer: 'shimmer 4s linear infinite',
        float: 'float 4s ease-in-out infinite',
        heroRise: 'heroRise 1s cubic-bezier(0.16,1,0.3,1) both',
        countUp: 'countUp 0.6s cubic-bezier(0.16,1,0.3,1) both',
        marquee: 'marquee 35s linear infinite',
      },
    },
  },
  plugins: [],
}
