
export const virtualReceptionistPricing = {
  eyebrow: 'Flat Rate - Unlimited Minutes - Dedicated Hours',
  heading: 'Virtual Receptionist Pricing',
  intro:
    'Get a dedicated virtual receptionist for calls, appointments, messages, and daily customer support without confusing per-minute charges.',
  trustNote: 'Save yourself from the hassle of complicated billing.',
  specialistTitle: 'Specialized receptionist options available with custom setups',
  specialistTags: ['HIPAA-Trained', 'B1 English Support', 'A-Level English Specialist', 'Bilingual Receptionist', 'Industry-Trained Support'],
  footnote: 'Secure your dedicated receptionist with your first month upfront.',
  plans: [
    {
      leftTag: 'Part-Time',
      rightTag: 'Flat Rate',
      name: 'Part-Time Virtual Receptionist',
      description: 'For businesses that need receptionist support during selected dedicated hours.',
      pricePrefix: 'Starting from',
      price: '$399',
      priceSuffix: '/month',
      features: [
        'Dedicated receptionist hours',
        'Unlimited minutes during coverage',
        'Appointment scheduling support',
        'Message taking and call notes',
      ],
      cta: 'Get Part-Time Support',
      href: '/contact-us',
    },
    {
      leftTag: 'Full-Time',
      rightTag: 'Flat Rate',
      name: 'Full-Time Virtual Receptionist',
      description: 'For growing businesses that need consistent receptionist coverage through the day.',
      pricePrefix: 'Starting from',
      price: '$799',
      priceSuffix: '/month',
      features: [
        'Full-time dedicated hours',
        'Unlimited minutes during coverage',
        'Appointment scheduling and reminders',
        'Lead capture and workflow updates',
      ],
      cta: 'Get Full-Time Support',
      href: '/contact-us',
      featured: true,
    },
    {
      leftTag: 'Custom',
      rightTag: 'Specialist',
      name: 'Custom Receptionist Setup',
      description: 'For special hours, advanced workflows, language preferences, or industry-specific support.',
      pricePrefix: 'Built around your needs',
      price: 'Custom',
      features: [
        'Custom dedicated hours',
        'Specialized receptionist options',
        'HIPAA-trained support available',
        'Advanced workflow instructions',
      ],
      cta: 'Request Custom Quote',
      href: '/contact-us',
    },
  ],
}

export const hipaaPricing = {
  eyebrow: 'Flat Rate - Unlimited Minutes - Dedicated HIPAA-Certified Hours',
  heading: 'HIPAA Certified Phone Answering Pricing',
  intro:
    'Premium medical answering support for clinics, healthcare offices, and patient-focused businesses that need certified, dedicated call handling.',
  trustNote: 'Save yourself from the hassle of complicated billing.',
  specialistTitle: 'Healthcare answering options available with custom setups',
  specialistTags: [
    'HIPAA-Certified Member',
    'Patient Intake Support',
    'Urgent Call Routing',
    'After-Hours Medical Answering',
    'Multi-Location Clinic Support',
  ],
  footnote: 'Secure your dedicated HIPAA-certified receptionist with your first month upfront.',
  plans: [
    {
      leftTag: 'Part-Time',
      rightTag: 'HIPAA Certified',
      name: 'Part-Time Medical Answering',
      description: 'For clinics and healthcare offices that need HIPAA-certified answering during selected dedicated hours.',
      pricePrefix: 'Starting',
      price: '$749',
      priceSuffix: '/month',
      features: [
        'HIPAA-certified answering member',
        'Unlimited minutes during coverage',
        'Patient call answering',
        'Appointment request handling',
      ],
      cta: 'Get Part-Time Support',
      href: '/contact-us',
    },
    {
      leftTag: 'Full-Time',
      rightTag: 'HIPAA Certified',
      name: 'Full-Time Medical Answering',
      description: 'For healthcare teams that need full-time HIPAA-certified call coverage and patient support.',
      pricePrefix: 'Starting',
      price: '$1,499',
      priceSuffix: '/month',
      features: [
        'Full-time HIPAA-certified hours',
        'Unlimited minutes during coverage',
        'Patient intake call support',
        'Urgent call routing instructions',
      ],
      cta: 'Get Full-Time Support',
      href: '/contact-us',
      featured: true,
    },
    {
      leftTag: 'Custom',
      rightTag: 'Healthcare',
      name: 'Custom Healthcare Answering',
      description: 'For advanced healthcare workflows, multi-location clinics, urgent routing, or after-hours medical support.',
      pricePrefix: 'Built around your clinic',
      price: 'Custom',
      features: [
        'Custom HIPAA-certified hours',
        'After-hours medical answering',
        'Multi-location clinic support',
        'Bilingual medical answering option',
      ],
      cta: 'Request Custom Quote',
      href: '/contact-us',
    },
  ],
}
